//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_gender { get; set; }
        public Nullable<System.DateTime> emp_adddate { get; set; }
        public Nullable<System.DateTime> emp_modifieddate { get; set; }
    }
}
